version: '3.8'

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${DB_PASSWORD}  # We will set this safely later
      - MYSQL_DB=healthfasta
      - FLASK_ENV=production           # Turns off Debug Mode
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:3000"  # Maps port 80 (Standard Web) to 3000 (React)
    depends_on:
      - backend

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: healthfasta
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./database/HealthFasta_SQL_script.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
