version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      # These names MUST match what is inside config.py
      - MYSQL_HOST=db 
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Claudio17.
      - MYSQL_DB=healthfasta
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    # This allows React to restart if it crashes
    restart: always 
    depends_on:
      - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: healthfasta
      MYSQL_ROOT_PASSWORD: Claudio17.
    ports:
      - "3306:3306"
    volumes:
      # This saves your data even if you restart the server
      - db_data:/var/lib/mysql
      - ./database/HealthFasta_SQL_script.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
